spring:
  datasource:
    url: jdbc:mysql://mysql:3306/scheduler
    username: nderim
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

server:
  port: 8080
