version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: softgardenscheduler-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduler
    ports:
      - "3306:3306"
